import copy
import numpy as np
from hgg.gcc_utils import gcc_load_lib, c_double, c_int
import torch
import torch.nn.functional as F
import time
from dt.models.decision_transformer import DecisionTransformer

def goal_distance(goal_a, goal_b):
	return np.linalg.norm(goal_a - goal_b, ord=2)
def goal_concat(obs, goal):
	return np.concatenate([obs, goal], axis=0)

class TrajectoryPool:
	def __init__(self, pool_length):
		self.length = pool_length
		self.pool = []
		self.pool_init_state = []
		self.counter = 0

	def insert(self, trajectory, init_state):
		if self.counter<self.length:
			self.pool.append(trajectory.copy())
			self.pool_init_state.append(init_state.copy())
		else:
			self.pool[self.counter%self.length] = trajectory.copy()
			self.pool_init_state[self.counter%self.length] = init_state.copy()
		self.counter += 1

	def pad(self):
		if self.counter>=self.length:
			return copy.deepcopy(self.pool), copy.deepcopy(self.pool_init_state)
		pool = copy.deepcopy(self.pool)
		pool_init_state = copy.deepcopy(self.pool_init_state)
		while len(pool)<self.length:
			pool += copy.deepcopy(self.pool)
			pool_init_state += copy.deepcopy(self.pool_init_state)
		return copy.deepcopy(pool[:self.length]), copy.deepcopy(pool_init_state[:self.length])
	
class DTSampler:
	def __init__(self, dt, achieved_trajectory_pool, num_episodes, add_noise_to_goal, normalize_aim_output, device = 'cuda' , trajectory_to_be_shorten = False, agent = None, init_goal = None) -> None:
		self.dt = dt
		self.achieved_trajectory_pool = achieved_trajectory_pool
		self.length = num_episodes
		self.add_noise_to_goal = add_noise_to_goal
		self.normalize_aim_output = normalize_aim_output
		self.device = device
		self.trajectory_to_be_shorten = trajectory_to_be_shorten 
		self.agent = agent
	


		# self.pool = np.tile(init_goal[np.newaxis,:],[self.length,1])+np.random.normal(0,self.delta,size=(self.length,self.dim))

		
	def train():
		obs = self.achieved_trajectory_pool
		
	def sample():
		return
	def update(self, desired_goals, replay_buffer = None):
		if self.achieved_trajectory_pool.counter == 0:
			self.pool = copy.deepcopy(desired_goals)
			return
		achieved_pool, achieved_pool_init_state = self.achieved_trajectory_pool.pad()

		if self.trajectory_to_be_shorten:
			achieved_pool = self.shorten_trajectory(achieved_pool = achieved_pool)
		
		assert len(achieved_pool) >= self.length
		assert self.agent.aim_discriminator is not None

		achieved_values = self.generate_achieved_values(achieved_pool_init_state, achieved_pool)
		self.normalize_achieved_value(achieved_values)

		self.train()
		self.generate_goals() # TODO : decide whether to have a pool of goals by or one goal generated by dt


	def add_noise():
		pass
	def generate_achieved_values(self,achieved_pool_init_state, achieved_pool):
		achieved_value = []		
		for i in range(len(achieved_pool)):
			 # maybe for all timesteps in an episode
			obs = [goal_concat(achieved_pool_init_state[i], achieved_pool[i][j]) for  j in range(achieved_pool[i].shape[0])] # list of [dim] (len = ts)
																															 # merge of achieved_pool and achieved_pool_init_state to draw trajectory
			
			with torch.no_grad(): ## when using no_grad, no gradients will be calculated or stored for operations on tensors, which can reduce memory usage and speed up computations				
				obs_t = torch.from_numpy(np.stack(obs, axis =0)).float().to(self.device) #[ts, dim]				
				if (self.agent.aim_discriminator is not None) and ('aim_f' in self.cost_type): # or value function is proxy for aim outputs
					value = -self.agent.aim_discriminator(obs_t).detach().cpu().numpy()[:, 0] 
																							  
																							
					# value = np.clip(value, -1.0/(1.0-self.gamma), 0)
			if 'aim_f' in self.cost_type:				
				achieved_value.append(value.copy())			
			elif 'meta_nml' in self.cost_type:			
				pass			
			else:
				raise NotImplementedError
		return achieved_value
	def normalize_achieved_value(self,achieved_value):
		if 'aim_f' in self.cost_type: #normalizing achieved_values
			# print('normalize aim output in hgg update!')
			# For considering different traj length
			aim_outputs_max = -np.inf
			aim_outputs_min = np.inf
			for i in range(len(achieved_value)): # list of aim_output [ts,]
				if achieved_value[i].max() > aim_outputs_max:
					aim_outputs_max = achieved_value[i].max()
				if achieved_value[i].min() < aim_outputs_min:
					aim_outputs_min = achieved_value[i].min()
			for i in range(len(achieved_value)):
				achieved_value[i] = ((achieved_value[i]-aim_outputs_min)/(aim_outputs_max - aim_outputs_min+0.00001)-0.5)*2 #[0, 1] -> [-1,1]
	def shorten_trajectory():
		pass
	def generate_goals():
		pass
	def generate_goal():
		pass
		
	
		
	